p[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
{
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]101[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract]*[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	
	p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	{
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]
		
		[[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]FF=[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]yp[qb2_abstract]=[qb2_abstract][qb2_abstract]pp[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x-f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])]
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract][qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X[qb2_abstract][qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X[qb2_abstract][qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]:V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k>[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k>()[qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<P[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<P[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>()[qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]PH[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]5[qb2_abstract]
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]()[qb2_abstract]
		{
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k(p[qb2_abstract][qb2_abstract]h:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
			
			[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k(p[qb2_abstract][qb2_abstract]h)[qb2_abstract]
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract])
			{
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][[qb2_abstract]][qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]y[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]y[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]
			}
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]h([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k)[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k)[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]wX:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract]
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
			{
				[qb2_abstract][qb2_abstract]wX[qb2_abstract]+=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]
			}
			
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]>=[qb2_abstract][qb2_abstract][qb2_abstract])
			{
				[qb2_abstract][qb2_abstract]wX[qb2_abstract]+=[qb2_abstract]5[qb2_abstract]
			}
			
			[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]=[qb2_abstract]p[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][[qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]-[qb2_abstract]1][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:P[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]P[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]h[qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract]wX,[qb2_abstract]0,[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]=[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract])[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]+[qb2_abstract]10[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]k,[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract]w[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]h([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]y[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]():v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract][qb2_abstract]=[qb2_abstract]13[qb2_abstract]
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X[qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract]
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X[qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]():v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]():v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
			{
				[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract])[qb2_abstract]
			}
		}
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
			{
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:P[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract]
				[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]==[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
				{
					h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract])[qb2_abstract]
					
				}
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				{
					[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract])[qb2_abstract]
				}
			}
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract]=[qb2_abstract]1[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x][qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k():[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k
		{
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]
		}
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract]=[qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]PH[qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]v[qb2_abstract]:[qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
			{
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:P[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract]
				[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]==[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
				{
					h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract])[qb2_abstract]
					
					[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]!=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]&&[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]!=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
					{
						[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract]
						[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]-[qb2_abstract],[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
					}
				}
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				{
					[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k([qb2_abstract])[qb2_abstract]
				}
			}
		}
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
			{
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][[qb2_abstract]][qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]z[qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]-[qb2_abstract][qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]60[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]3
			}
		}
	}
}