p[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
{
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]
	
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]
	
	[qb2_abstract]**
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	[qb2_abstract]*[qb2_abstract]@[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	{		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>[qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p:[qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p()[qb2_abstract]
		{
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]10[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]150[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]5[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]10[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]80[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p-[qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>([qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y[qb2_abstract]*[qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>([qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y[qb2_abstract]*[qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]1:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X([qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X([qb2_abstract]-[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](([qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y-1)[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
			{
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]1[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract]+[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y([qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract]x,[qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract]y,[qb2_abstract][qb2_abstract])[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract]+[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract]+[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y][qb2_abstract]x,[qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract][qb2_abstract]+[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y][qb2_abstract]y,[qb2_abstract][qb2_abstract][qb2_abstract]+[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y)[qb2_abstract]
				
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]])[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]+[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]y])[qb2_abstract]
			}
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract]p[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]()[qb2_abstract]
			[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract]p)[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract]j:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract]j[qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j++)[qb2_abstract]
			{
				[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](),[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]1))[qb2_abstract]
			}
			
			[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ff)[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]v[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{			
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]yp[qb2_abstract][qb2_abstract]==[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract])
			{
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]-[qb2_abstract]1)[qb2_abstract]
				
				[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			}
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
			{
				[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			}
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ff([qb2_abstract]v[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
			{
				v[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Y)[qb2_abstract]
				
				[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract]h[qb2_abstract]wh[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				v[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]hV[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x)[qb2_abstract]
				[qb2_abstract][qb2_abstract]hV[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract]py(p[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]
				[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ky[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				[qb2_abstract][qb2_abstract]---[qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]-[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract]
				[qb2_abstract]f[qb2_abstract]([qb2_abstract]!p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
				{
					[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]=[qb2_abstract]p[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]
					[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]=[qb2_abstract]p[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]
					
					v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]pV[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x)[qb2_abstract]
					[qb2_abstract][qb2_abstract]pV[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract]py(p[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				}
			}
		}
		
		[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]([qb2_abstract]v[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]yp[qb2_abstract][qb2_abstract]==[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
			{
				f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
				{
					[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
					[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]])[qb2_abstract]
				}
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ff)[qb2_abstract]
			}
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			{
				f[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
				{
					[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
					[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][[qb2_abstract]])[qb2_abstract]
				}
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ff)[qb2_abstract]
				
				[qb2_abstract]f[qb2_abstract]([qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
				{
					[qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				}
			}
		}
	}
}

[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]
[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]

[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]J[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
{
	[[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]='[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f')]
	p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	
	p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		
	p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Y:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
	{
		v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
		[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
		[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]=[qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]=[qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X[qb2_abstract]
		[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Y[qb2_abstract]
		[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract]
		
		[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	}
	
	p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x():[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		{[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract]}
}