p[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
{
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	
	
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]15[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	
	[qb2_abstract]**
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Phy[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]::[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]w[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	[qb2_abstract]*[qb2_abstract]@[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	{
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract]P[qb2_abstract][qb2_abstract]y([qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]3,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]),[qb2_abstract]50)[qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y([qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]*[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]3),[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]),[qb2_abstract]100,[qb2_abstract]50,[qb2_abstract]10,[qb2_abstract]1,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]15)[qb2_abstract]
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
		{
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract](j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]():v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			
			[qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]()[qb2_abstract]
			{
				[qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]hF[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](0xff0000[qb2_abstract]|[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract])[qb2_abstract]
				{
					p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w([qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]5,[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
					p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w([qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]5,[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				}
				[qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]pF[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
			}
			[qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]()[qb2_abstract]
				
			
			[qb2_abstract]f[qb2_abstract]([qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
			{
				[qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]([qb2_abstract],[qb2_abstract]0xff0000[qb2_abstract]|[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract])[qb2_abstract]
				{
					v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w([qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]0,[qb2_abstract]0)[qb2_abstract]
				}
				[qb2_abstract][qb2_abstract][qb2_abstract]ph[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]()[qb2_abstract]
			}
		}
	}
}