p[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
{
	
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Phy[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]
	
	[qb2_abstract]**
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract]Y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]f[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]Y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]ff[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	[qb2_abstract]*[qb2_abstract]@[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	{
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]50[qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract]K[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]10[qb2_abstract]

		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
		{
			[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]5[qb2_abstract]
			
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]10[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]80[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract]j:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract]j[qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j++)[qb2_abstract]
			{
				[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](),[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]1))[qb2_abstract]
			}
			
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k:V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]>()[qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]v[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract]f[qb2_abstract]([qb2_abstract]![qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract])[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Y)[qb2_abstract]
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]>=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
			{
				p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]p[qb2_abstract][qb2_abstract]h([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				f[qb2_abstract][qb2_abstract][qb2_abstract]hP[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
				
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			}
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]hP[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]():v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
			{
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			}
			
			[qb2_abstract]f[qb2_abstract]([qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]==[qb2_abstract]1[qb2_abstract])
			{
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y()[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[0][qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]([qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract](),[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract]K[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]))[qb2_abstract]
			}
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			{
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]wP[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y(p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract]K[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]0,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			}
			
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]v[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Y)[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]yp[qb2_abstract][qb2_abstract]==[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract])
			{
				f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
				{
					v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Phy[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract])[qb2_abstract]
					[qb2_abstract]f[qb2_abstract]([qb2_abstract]!([qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract])[qb2_abstract])[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
					
					[qb2_abstract]f[qb2_abstract]([qb2_abstract]([qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract])[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract])
					{
						[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
					}
				}
			}
			
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]yp[qb2_abstract][qb2_abstract]==[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract])
			{
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]p[qb2_abstract][qb2_abstract]h([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			}
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			{
				[qb2_abstract]f([qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]==[qb2_abstract]1[qb2_abstract])
					f[qb2_abstract][qb2_abstract][qb2_abstract]hP[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
				
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract]=[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]=[qb2_abstract]0[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				
				w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			}
		}
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]([qb2_abstract]v[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]yp[qb2_abstract][qb2_abstract]==[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
			{
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			}
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			{
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				
				[qb2_abstract]f[qb2_abstract]([qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])
				{
					[qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				}
			}
		}
		
	}

}