p[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
{
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]hK[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]J[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Phy[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]
	[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]
	
	[qb2_abstract]**
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	[qb2_abstract]*[qb2_abstract]@[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	[qb2_abstract]*[qb2_abstract]
	p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	{
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]
		
		p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract]
		{
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]40[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]1[qb2_abstract]0[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]yH[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]40[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]300,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]00,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]10[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p()[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract]1:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X([qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]),[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]1)[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]),[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]1)[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y:[qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Y([qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]),[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract]+[qb2_abstract]10,[qb2_abstract]0),[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]yH[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract],[qb2_abstract]18,[qb2_abstract]0,[qb2_abstract][qb2_abstract][qb2_abstract]*[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract],[qb2_abstract][qb2_abstract])[qb2_abstract]
			wh[qb2_abstract][qb2_abstract][qb2_abstract]1[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			wh[qb2_abstract][qb2_abstract][qb2_abstract]1[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]1[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]w[qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]J[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]J[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y,[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract]1,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X([qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]),[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract]1[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]J[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]J[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y,[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]X([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]),[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract]=[qb2_abstract]40[qb2_abstract]
			[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]75[qb2_abstract]
			[qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]J[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y)[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract](wh[qb2_abstract][qb2_abstract][qb2_abstract]1)[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract](wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y([qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]W[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]),[qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]V[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]-[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract],[qb2_abstract]0),[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract]1[qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]*[qb2_abstract]85,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract]*[qb2_abstract]1[qb2_abstract]5,[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]+=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p)[qb2_abstract]
			
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]k[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]hK[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
			
			[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]P[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract],[qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
		}
		
		p[qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]v[qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]p[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract]):v[qb2_abstract][qb2_abstract][qb2_abstract]
		{
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]k[qb2_abstract]wh[qb2_abstract][qb2_abstract]h[qb2_abstract]k[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract]0[qb2_abstract]
			v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract]
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]hK[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract]y[qb2_abstract][qb2_abstract]w[qb2_abstract](K[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract],[qb2_abstract]K[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract])
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]-=[qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
			[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]F[qb2_abstract][qb2_abstract][qb2_abstract]hK[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]()[qb2_abstract][qb2_abstract][qb2_abstract]K[qb2_abstract]y[qb2_abstract][qb2_abstract]w[qb2_abstract](K[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]H[qb2_abstract],[qb2_abstract]K[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract])
				[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]+=[qb2_abstract][qb2_abstract][qb2_abstract]x[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
	
			[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]'[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]f[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract]h[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]w[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract])[qb2_abstract]
			f[qb2_abstract][qb2_abstract][qb2_abstract](v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract]0[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]<[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]++)[qb2_abstract]
			{
				[qb2_abstract][qb2_abstract]---[qb2_abstract][qb2_abstract]pp[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract][qb2_abstract]wh[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]
				v[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract]:[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]Phy[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]=[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract])[qb2_abstract]
				[qb2_abstract]f[qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract])
				{
					([qb2_abstract][qb2_abstract]j[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]h[qb2_abstract]p[qb2_abstract])[qb2_abstract][qb2_abstract]pp[qb2_abstract]y[qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract]([qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract][qb2_abstract])[qb2_abstract]
				}
			}
		}
	}
}